In [1]:
import datetime
import os.path
import sys

from my_libs import *

/home/ken/.local/lib/python2.7/site-packages/pyfolio/pos.py:28: UserWarning: Module "zipline.assets" not found; mutltipliers will not be applied to position notionals.
  ' to position notionals.'

In [2]:
robinhood = robingateway()

robinhood.my_trader.get_mfa_token("PQZJUCVO4CNVUWYP")

u'155051'

In [20]:
robinhood.place_buy_bulk_checkup(ticker_list=["TSLA"],quantity_list=[1],price_list=[160])

SPY 25.00000000
CCI 3.00000000
VIXY 37.00000000
GLD 15.00000000
ABBV 6.00000000
FCO 42.00000000
DFIN 25.00000000
('Ticker found in instruments :', 'TSLA')

KeyboardInterrupt:

In [15]:
float(robinhood.my_trader.get_quote("AAPL")["last_trade_price"])

450.91

In [12]:
realtimequote("CCC")

,avgVolume,change,changesPercentage,dayHigh,dayLow,earningsAnnouncement,eps,exchange,marketCap,name,open,pe,previousClose,price,priceAvg200,priceAvg50,sharesOutstanding,symbol,timestamp,volume,yearHigh,yearLow
0,1725571,-0.3094,-1.0700,28.8900,28.0100,2020-07-30T06:00:25.000+0000,-0.4490,NYSE,"11,071,181,824.0000",Clarivate Analytics Plc,28.7800,None,28.8900,28.5806,22.3347,24.1847,387367019,CCC,1597074313,248969,29.9500,15.0000

In [4]:
float(robinhood.get_average_cost("VIXY"))

27.08

In [10]:
vwap("TSLA",back_day=2)

All price data of Close is actually Adj Close
('Finished', u'TSLA')

403.89483511193

In [5]:
robinhood.my_trader.get_popularity("GLD")

22723

In [5]:
get_price_data(["AAPL"], method = "realtimeday", back_day = 0)

All price data of Close is actually Adj Close
('Finished', u'AAPL')

Empty DataFrame
Columns: [adjClose, change, changeOverTime, changePercent, Close, TimeStamp, High, label, Low, Open, unadjustedVolume, Volume, vwap, Ticker, Return, Fwd_Return]
Index: []

In [ ]:
backtest("SNCR",cciStrategy,method="self_minute", back_day = 80)

In [7]:
momentum_backtest("AAPL",20,20,robinhood=robinhood,method = 'self_minute')

All price data of Close is actually Adj Close
Connection Successful
('Finished', 'AAPL')
2020-05-05T15:30:00, BUY CREATE, 298.87, position value: 2000.00
2020-05-05T15:30:00, ORDER ACCEPTED/SUBMITTED
2020-05-05T15:30:00, ORDER ACCEPTED/SUBMITTED
2020-05-05T15:30:00, ORDER ACCEPTED/SUBMITTED
2020-05-05T16:00:00, BUY EXECUTED, Price: 298.87, Cost: 1793.22, Comm 1.79
2020-05-07T11:30:00, SELL CREATE, 303.16, position value: 2023.95
2020-05-07T11:30:00, ORDER ACCEPTED/SUBMITTED
2020-05-07T11:30:00, ORDER ACCEPTED/SUBMITTED
2020-05-07T11:30:00, ORDER ACCEPTED/SUBMITTED
2020-05-07T12:00:00, SELL EXECUTED, Price: 303.16, Cost: 1793.22, Comm 1.82
2020-05-07T12:00:00, BUY CREATE, 303.92, position value: 2022.13
2020-05-07T12:00:00, ORDER ACCEPTED/SUBMITTED
2020-05-07T12:00:00, ORDER ACCEPTED/SUBMITTED
2020-05-07T12:00:00, ORDER ACCEPTED/SUBMITTED
2020-05-07T12:30:00, BUY EXECUTED, Price: 303.85, Cost: 1823.10, Comm 1.82
2020-05-08T15:00:00, SELL CREATE, 307.68, position value: 2043.26
2020-05-08T15:00:00, ORDER ACCEPTED/SUBMITTED
2020-05-08T15:00:00, ORDER ACCEPTED/SUBMITTED
2020-05-08T15:00:00, ORDER ACCEPTED/SUBMITTED
2020-05-08T15:30:00, SELL EXECUTED, Price: 309.10, Cost: 1823.10, Comm 1.85
2020-05-08T15:30:00, BUY CREATE, 309.61, position value: 2049.95
2020-05-08T15:30:00, ORDER ACCEPTED/SUBMITTED
2020-05-08T15:30:00, ORDER ACCEPTED/SUBMITTED
2020-05-08T15:30:00, ORDER ACCEPTED/SUBMITTED
2020-05-08T16:00:00, BUY EXECUTED, Price: 309.61, Cost: 1857.66, Comm 1.86
2020-05-13T09:30:00, SELL CREATE, 311.41, position value: 2058.89
2020-05-13T09:30:00, ORDER ACCEPTED/SUBMITTED
2020-05-13T09:30:00, ORDER ACCEPTED/SUBMITTED
2020-05-13T09:30:00, ORDER ACCEPTED/SUBMITTED
2020-05-13T10:00:00, SELL EXECUTED, Price: 311.41, Cost: 1857.66, Comm 1.87
2020-05-13T10:00:00, BUY CREATE, 313.09, position value: 2057.02
2020-05-13T10:00:00, ORDER ACCEPTED/SUBMITTED
2020-05-13T10:00:00, ORDER ACCEPTED/SUBMITTED
2020-05-13T10:00:00, ORDER ACCEPTED/SUBMITTED
2020-05-13T10:30:00, BUY EXECUTED, Price: 314.71, Cost: 1888.26, Comm 1.89
2020-05-14T13:00:00, SELL CREATE, 306.04, position value: 2003.12
2020-05-14T13:00:00, ORDER ACCEPTED/SUBMITTED
2020-05-14T13:00:00, ORDER ACCEPTED/SUBMITTED
2020-05-14T13:00:00, ORDER ACCEPTED/SUBMITTED
2020-05-14T13:30:00, SELL EXECUTED, Price: 306.04, Cost: 1888.26, Comm 1.84
2020-05-14T15:30:00, BUY CREATE, 307.99, position value: 2001.28
2020-05-14T15:30:00, ORDER ACCEPTED/SUBMITTED
2020-05-14T15:30:00, ORDER ACCEPTED/SUBMITTED
2020-05-14T15:30:00, ORDER ACCEPTED/SUBMITTED
2020-05-14T16:00:00, BUY EXECUTED, Price: 307.99, Cost: 1847.94, Comm 1.85
2020-05-18T11:30:00, SELL CREATE, 313.55, position value: 2032.79
2020-05-18T11:30:00, ORDER ACCEPTED/SUBMITTED
2020-05-18T11:30:00, ORDER ACCEPTED/SUBMITTED
2020-05-18T11:30:00, ORDER ACCEPTED/SUBMITTED
2020-05-18T12:00:00, SELL EXECUTED, Price: 313.83, Cost: 1847.94, Comm 1.88
2020-05-18T12:00:00, BUY CREATE, 313.95, position value: 2032.59
2020-05-18T12:00:00, ORDER ACCEPTED/SUBMITTED
2020-05-18T12:00:00, ORDER ACCEPTED/SUBMITTED
2020-05-18T12:00:00, ORDER ACCEPTED/SUBMITTED
2020-05-18T12:30:00, BUY EXECUTED, Price: 313.95, Cost: 1883.70, Comm 1.88
2020-05-19T15:00:00, SELL CREATE, 314.80, position value: 2035.81
2020-05-19T15:00:00, ORDER ACCEPTED/SUBMITTED
2020-05-19T15:00:00, ORDER ACCEPTED/SUBMITTED
2020-05-19T15:00:00, ORDER ACCEPTED/SUBMITTED
2020-05-19T15:30:00, SELL EXECUTED, Price: 314.80, Cost: 1883.70, Comm 1.89
2020-05-19T15:30:00, BUY CREATE, 315.90, position value: 2033.92
2020-05-19T15:30:00, ORDER ACCEPTED/SUBMITTED
2020-05-19T15:30:00, ORDER ACCEPTED/SUBMITTED
2020-05-19T15:30:00, ORDER ACCEPTED/SUBMITTED
2020-05-19T16:00:00, BUY EXECUTED, Price: 315.90, Cost: 1895.41, Comm 1.90
2020-05-21T11:30:00, SELL CREATE, 316.83, position value: 2037.61
2020-05-21T11:30:00, ORDER ACCEPTED/SUBMITTED
2020-05-21T11:30:00, ORDER ACCEPTED/SUBMITTED
2020-05-21T11:30:00, ORDER ACCEPTED/SUBMITTED
2020-05-21T12:00:00, SELL EXECUTED, Price: 316.83, Cost: 1895.41, Comm 1.90
2020-05-21T12:00:00, BUY CREATE, 317.12, position value: 2035.71
2020-05-21T12:00:00, ORDER ACCEPTED/SUBMITTED
2020-05-21T12:00:00, ORDER ACCEPTED/SUBMITTED
2020-05-21T12:00:00, ORDER ACCEPTED/SUBMITTED
2020-05-21T12:30:00, BUY EXECUTED, Price: 317.54, Cost: 1905.24, Comm 1.91
2020-05-22T15:00:00, SELL CREATE, 318.21, position value: 2037.83
2020-05-22T15:00:00, ORDER ACCEPTED/SUBMITTED
2020-05-22T15:00:00, ORDER ACCEPTED/SUBMITTED
2020-05-22T15:00:00, ORDER ACCEPTED/SUBMITTED
2020-05-22T15:30:00, SELL EXECUTED, Price: 318.46, Cost: 1905.24, Comm 1.91
2020-05-22T15:30:00, BUY CREATE, 317.63, position value: 2037.42
2020-05-22T15:30:00, ORDER ACCEPTED/SUBMITTED
2020-05-22T15:30:00, ORDER ACCEPTED/SUBMITTED
2020-05-22T15:30:00, ORDER ACCEPTED/SUBMITTED
2020-05-22T16:00:00, BUY EXECUTED, Price: 317.63, Cost: 1905.78, Comm 1.91
2020-05-27T11:30:00, SELL CREATE, 315.33, position value: 2021.71
2020-05-27T11:30:00, ORDER ACCEPTED/SUBMITTED
2020-05-27T11:30:00, ORDER ACCEPTED/SUBMITTED
2020-05-27T11:30:00, ORDER ACCEPTED/SUBMITTED
2020-05-27T12:00:00, SELL EXECUTED, Price: 314.89, Cost: 1905.78, Comm 1.89
2020-05-28T10:30:00, BUY CREATE, 320.35, position value: 2017.18
2020-05-28T10:30:00, ORDER ACCEPTED/SUBMITTED
2020-05-28T10:30:00, ORDER ACCEPTED/SUBMITTED
2020-05-28T10:30:00, ORDER ACCEPTED/SUBMITTED
2020-05-28T11:00:00, BUY EXECUTED, Price: 320.35, Cost: 1922.10, Comm 1.92
2020-05-29T13:30:00, SELL CREATE, 318.93, position value: 2006.74
2020-05-29T13:30:00, ORDER ACCEPTED/SUBMITTED
2020-05-29T13:30:00, ORDER ACCEPTED/SUBMITTED
2020-05-29T13:30:00, ORDER ACCEPTED/SUBMITTED
2020-05-29T14:00:00, SELL EXECUTED, Price: 318.73, Cost: 1922.10, Comm 1.91
2020-06-01T12:00:00, BUY CREATE, 320.74, position value: 2003.61
2020-06-01T12:00:00, ORDER ACCEPTED/SUBMITTED
2020-06-01T12:00:00, ORDER ACCEPTED/SUBMITTED
2020-06-01T12:00:00, ORDER ACCEPTED/SUBMITTED
2020-06-01T12:30:00, BUY EXECUTED, Price: 320.73, Cost: 1924.38, Comm 1.92
2020-06-02T15:00:00, SELL CREATE, 322.06, position value: 2009.66
2020-06-02T15:00:00, ORDER ACCEPTED/SUBMITTED
2020-06-02T15:00:00, ORDER ACCEPTED/SUBMITTED
2020-06-02T15:00:00, ORDER ACCEPTED/SUBMITTED
2020-06-02T15:30:00, SELL EXECUTED, Price: 322.06, Cost: 1924.38, Comm 1.93
2020-06-02T15:30:00, BUY CREATE, 321.84, position value: 2007.73
2020-06-02T15:30:00, ORDER ACCEPTED/SUBMITTED
2020-06-02T15:30:00, ORDER ACCEPTED/SUBMITTED
2020-06-02T15:30:00, ORDER ACCEPTED/SUBMITTED
2020-06-02T16:00:00, BUY EXECUTED, Price: 321.84, Cost: 1931.04, Comm 1.93
2020-06-04T11:30:00, SELL CREATE, 323.38, position value: 2015.04
2020-06-04T11:30:00, ORDER ACCEPTED/SUBMITTED
2020-06-04T11:30:00, ORDER ACCEPTED/SUBMITTED
2020-06-04T11:30:00, ORDER ACCEPTED/SUBMITTED
2020-06-04T12:00:00, SELL EXECUTED, Price: 323.38, Cost: 1931.04, Comm 1.94
2020-06-04T12:00:00, BUY CREATE, 324.06, position value: 2013.10
2020-06-04T12:00:00, ORDER ACCEPTED/SUBMITTED
2020-06-04T12:00:00, ORDER ACCEPTED/SUBMITTED
2020-06-04T12:00:00, ORDER ACCEPTED/SUBMITTED
2020-06-04T12:30:00, BUY EXECUTED, Price: 323.95, Cost: 1943.68, Comm 1.94
2020-06-05T15:00:00, SELL CREATE, 330.22, position value: 2048.79
2020-06-05T15:00:00, ORDER ACCEPTED/SUBMITTED
2020-06-05T15:00:00, ORDER ACCEPTED/SUBMITTED
2020-06-05T15:00:00, ORDER ACCEPTED/SUBMITTED
2020-06-05T15:30:00, SELL EXECUTED, Price: 330.22, Cost: 1943.68, Comm 1.98
2020-06-05T15:30:00, BUY CREATE, 331.47, position value: 2046.81
2020-06-05T15:30:00, ORDER ACCEPTED/SUBMITTED
2020-06-05T15:30:00, ORDER ACCEPTED/SUBMITTED
2020-06-05T15:30:00, ORDER ACCEPTED/SUBMITTED
2020-06-05T16:00:00, BUY EXECUTED, Price: 330.45, Cost: 1982.70, Comm 1.98
2020-06-09T11:30:00, SELL CREATE, 341.52, position value: 2111.25
2020-06-09T11:30:00, ORDER ACCEPTED/SUBMITTED
2020-06-09T11:30:00, ORDER ACCEPTED/SUBMITTED
2020-06-09T11:30:00, ORDER ACCEPTED/SUBMITTED
2020-06-09T12:00:00, SELL EXECUTED, Price: 341.52, Cost: 1982.70, Comm 2.05
2020-06-09T12:00:00, BUY CREATE, 341.08, position value: 2109.20
2020-06-09T12:00:00, ORDER ACCEPTED/SUBMITTED
2020-06-09T12:00:00, ORDER ACCEPTED/SUBMITTED
2020-06-09T12:00:00, ORDER ACCEPTED/SUBMITTED
2020-06-09T12:30:00, BUY EXECUTED, Price: 343.14, Cost: 2058.84, Comm 2.06
2020-06-10T15:00:00, SELL CREATE, 352.47, position value: 2163.12
2020-06-10T15:00:00, ORDER ACCEPTED/SUBMITTED
2020-06-10T15:00:00, ORDER ACCEPTED/SUBMITTED
2020-06-10T15:00:00, ORDER ACCEPTED/SUBMITTED
2020-06-10T15:30:00, SELL EXECUTED, Price: 352.47, Cost: 2058.84, Comm 2.11
2020-06-10T15:30:00, BUY CREATE, 354.36, position value: 2161.01
2020-06-10T15:30:00, ORDER ACCEPTED/SUBMITTED
2020-06-10T15:30:00, ORDER ACCEPTED/SUBMITTED
2020-06-10T15:30:00, ORDER ACCEPTED/SUBMITTED
2020-06-10T16:00:00, BUY EXECUTED, Price: 354.19, Cost: 2125.14, Comm 2.13
2020-06-12T11:30:00, SELL CREATE, 337.78, position value: 2060.40
2020-06-12T11:30:00, ORDER ACCEPTED/SUBMITTED
2020-06-12T11:30:00, ORDER ACCEPTED/SUBMITTED
2020-06-12T11:30:00, ORDER ACCEPTED/SUBMITTED
2020-06-12T12:00:00, SELL EXECUTED, Price: 337.78, Cost: 2125.14, Comm 2.03
2020-06-15T11:30:00, BUY CREATE, 337.02, position value: 2058.37
2020-06-15T11:30:00, ORDER ACCEPTED/SUBMITTED
2020-06-15T11:30:00, ORDER ACCEPTED/SUBMITTED
2020-06-15T11:30:00, ORDER ACCEPTED/SUBMITTED
2020-06-15T12:00:00, BUY EXECUTED, Price: 337.69, Cost: 2026.14, Comm 2.03
2020-06-16T14:30:00, SELL CREATE, 352.26, position value: 2143.78
2020-06-16T14:30:00, ORDER ACCEPTED/SUBMITTED
2020-06-16T14:30:00, ORDER ACCEPTED/SUBMITTED
2020-06-16T14:30:00, ORDER ACCEPTED/SUBMITTED
2020-06-16T15:00:00, SELL EXECUTED, Price: 351.83, Cost: 2026.14, Comm 2.11
2020-06-16T15:00:00, BUY CREATE, 351.33, position value: 2139.08
2020-06-16T15:00:00, ORDER ACCEPTED/SUBMITTED
2020-06-16T15:00:00, ORDER ACCEPTED/SUBMITTED
2020-06-16T15:00:00, ORDER ACCEPTED/SUBMITTED
2020-06-16T15:30:00, BUY EXECUTED, Price: 351.33, Cost: 2107.98, Comm 2.11

2020-06-18T11:00:00, SELL CREATE, 352.42, position value: 2143.51
2020-06-18T11:00:00, ORDER ACCEPTED/SUBMITTED
2020-06-18T11:00:00, ORDER ACCEPTED/SUBMITTED
2020-06-18T11:00:00, ORDER ACCEPTED/SUBMITTED
2020-06-18T11:30:00, SELL EXECUTED, Price: 353.17, Cost: 2107.98, Comm 2.12
2020-06-18T11:30:00, BUY CREATE, 352.75, position value: 2145.89
2020-06-18T11:30:00, ORDER ACCEPTED/SUBMITTED
2020-06-18T11:30:00, ORDER ACCEPTED/SUBMITTED
2020-06-18T11:30:00, ORDER ACCEPTED/SUBMITTED
2020-06-18T12:00:00, BUY EXECUTED, Price: 352.75, Cost: 2116.50, Comm 2.12
2020-06-19T14:30:00, SELL CREATE, 345.81, position value: 2102.14
2020-06-19T14:30:00, ORDER ACCEPTED/SUBMITTED
2020-06-19T14:30:00, ORDER ACCEPTED/SUBMITTED
2020-06-19T14:30:00, ORDER ACCEPTED/SUBMITTED
2020-06-19T15:00:00, SELL EXECUTED, Price: 345.81, Cost: 2116.50, Comm 2.07
2020-06-22T10:00:00, BUY CREATE, 354.85, position value: 2100.06
2020-06-22T10:00:00, ORDER ACCEPTED/SUBMITTED
2020-06-22T10:00:00, ORDER ACCEPTED/SUBMITTED
2020-06-22T10:00:00, ORDER ACCEPTED/SUBMITTED
2020-06-22T10:30:00, BUY EXECUTED, Price: 355.31, Cost: 1776.55, Comm 1.78
Good Trade
Final Portfolio Value: 2117.33

2117.3339098000015

In [2]:
log_trade("AIG",1, 13.3, "test" , hold_days = 3, database = "trade_log")

Connection Successful

InternalError: (pymysql.err.InternalError) (1054, u"Unknown column 'Hold_days' in 'field list'")
[SQL: INSERT INTO trade_log.`AIG` (`Hold_days`, `Price`, `Strategy`, `Ticker`, `TimeStamp`, size) VALUES (%(Hold_days)s, %(Price)s, %(Strategy)s, %(Ticker)s, %(TimeStamp)s, %(size)s)]
[parameters: {'TimeStamp': datetime.datetime(2020, 6, 3, 8, 30, 22, 149119), 'Price': 13.3, 'Strategy': 'test', 'Ticker': 'AIG', 'Hold_days': 3, 'size': 1}]
(Background on this error at: http://sqlalche.me/e/2j85)

In [3]:
log = get_trade_log("STMP")

Connection Successful

In [6]:
 log["size"].iloc[-1]

-3.0

In [87]:
robinhood.my_trader.positions()["results"]

In [97]:


database = "trade_log"
myfilter = 'momentum'
mongod = mongo()
working = mongod.conn.get_data('''

SELECT table_name FROM information_schema.tables
WHERE table_schema = '%s';

'''%database)["table_name"]
sent = []
for i in working:
    temp = get_trade_log(i)
    if len(temp) > 0 and temp["size"].sum() != 0 and temp["Strategy"].iloc[0]==myfilter:
        sent.append(i)

Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful

In [2]:
get_open_opsition()

Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful

['AKCA', 'BIPC', 'CCI', 'FCO', 'FCT', 'HCM', 'NOMD', 'PEJ']

In [3]:
get_open_opsition(stratgy_filter="momentum")

Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful

['AKCA', 'BIPC', 'FCO', 'FCT', 'HCM', 'NOMD', 'PEJ']

--------

----------------

## VIX Trade

In [4]:
vix_trade = vix_dayroll_trade(robinhood)

In [5]:
vix_trade.trade_action()

All price data of Close is actually Adj Close
Connection Successful
exceptions must be old-style classes or derived from BaseException, not NoneType
switching to realtimeday method
('Finished', '^VIX')
VXJ20
Downloading Date: 2020-04-15

Enter larger than, Exit less than
              Close_x  Close_y  Day_Roll
TimeStamp
2020-02-10  15.040000    16.48       NaN
2020-02-11  15.180000    16.45       NaN
2020-02-12  13.740000    16.11       NaN
2020-02-13  14.150000    16.30       NaN
2020-02-14  13.680000    16.11       NaN
2020-02-18  14.830000    16.55       NaN
2020-02-19  14.380000    16.27       NaN
2020-02-20  15.560000    16.90       NaN
2020-02-21  17.080000    17.33       NaN
2020-02-24  25.030001    19.40 -0.055684
2020-02-25  27.850000    20.67 -0.047476
2020-02-26  27.559999    21.03 -0.036622
2020-02-27  39.160000    23.62 -0.060339
2020-02-28  40.110001    23.00 -0.056474
2020-03-02  33.419998    23.30 -0.034115
2020-03-03  36.820000    25.50 -0.038919
2020-03-04  31.990000    24.70 -0.028461
2020-03-05  39.619999    27.52 -0.053670
2020-03-06  41.939999    30.65 -0.062202
2020-03-09  54.459999    37.20 -0.072912
2020-03-10  47.299999    34.55 -0.055199
2020-03-11  53.900002    39.05 -0.063743
2020-03-12  75.470001    47.35 -0.071835
2020-03-13  57.830002    44.80 -0.032335
2020-03-16  82.690002    58.85 -0.048230
2020-03-17  75.910004    60.70 -0.029738
2020-03-18  76.449997    71.15 -0.011173
2020-03-19  72.000000    68.20 -0.008864
2020-03-20  66.040001    62.00 -0.011174
2020-03-23  61.590000    49.40 -0.035404
2020-03-24  61.669998    46.75 -0.052503
2020-03-25  63.950001    51.31 -0.051266
2020-03-26  61.000000    46.35 -0.058859
2020-03-27  65.540001    53.40 -0.053364
2020-03-30  57.080002    49.65 -0.037602
2020-03-31  53.540001    47.25 -0.031335
Connection Successful
Connection Successful
VXJ20
VXJ20
Downloading Date: 2020-04-15
SPY 16.00000000
SVXY 26.00000000
no long trade signal

Day roll is -0.0239

Day roll enter signal is -0.0381

Day roll exit signal is -0.0553

Day roll buy enter signal is -0.0729

Day roll buy exit signal is -0.0628

In [5]:
vix_trade.vix_trade_signal()

All price data of Close is actually Adj Close
Connection Successful
exceptions must be old-style classes or derived from BaseException, not NoneType
switching to realtimeday method
('Finished', '^VIX')
VXJ20
Downloading Date: 2020-04-15

Enter larger than, Exit less than
              Close_x  Close_y  Day_Roll
TimeStamp
2020-02-10  15.040000    16.48       NaN
2020-02-11  15.180000    16.45       NaN
2020-02-12  13.740000    16.11       NaN
2020-02-13  14.150000    16.30       NaN
2020-02-14  13.680000    16.11       NaN
2020-02-18  14.830000    16.55       NaN
2020-02-19  14.380000    16.27       NaN
2020-02-20  15.560000    16.90       NaN
2020-02-21  17.080000    17.33       NaN
2020-02-24  25.030001    19.40 -0.055684
2020-02-25  27.850000    20.67 -0.047476
2020-02-26  27.559999    21.03 -0.036622
2020-02-27  39.160000    23.62 -0.060339
2020-02-28  40.110001    23.00 -0.056474
2020-03-02  33.419998    23.30 -0.034115
2020-03-03  36.820000    25.50 -0.038919
2020-03-04  31.990000    24.70 -0.028461
2020-03-05  39.619999    27.52 -0.053670
2020-03-06  41.939999    30.65 -0.062202
2020-03-09  54.459999    37.20 -0.072912
2020-03-10  47.299999    34.55 -0.055199
2020-03-11  53.900002    39.05 -0.063743
2020-03-12  75.470001    47.35 -0.071835
2020-03-13  57.830002    44.80 -0.032335
2020-03-16  82.690002    58.85 -0.048230
2020-03-17  75.910004    60.70 -0.029738
2020-03-18  76.449997    71.15 -0.011173
2020-03-19  72.000000    68.20 -0.008864
2020-03-20  66.040001    62.00 -0.011174
2020-03-23  61.590000    49.40 -0.035404
2020-03-24  61.669998    46.75 -0.052503
2020-03-25  63.950001    51.31 -0.051266
2020-03-26  61.000000    46.35 -0.058859
2020-03-27  65.540001    53.40 -0.053364
2020-03-30  57.080002    49.65 -0.037602
2020-03-31  53.540001    47.25 -0.031335

(-0.03812896742150494,
 -0.055296277389379055,
 -0.07291182832737012,
 -0.06281797725692806)

In [7]:
vix_enter, vix_exit, vix_buy_enter, vix_buy_exit = vix_trade.vix_trade_signal()

All price data of Close is actually Adj Close
Connection Successful
exceptions must be old-style classes or derived from BaseException, not NoneType
switching to realtimeday method
('Finished', '^VIX')
VXH20
The previous symbol not available, changed to: VXJ20
Downloading Date: 2020-04-15

Enter larger than, Exit less than
              Close_x  Close_y  Day_Roll
TimeStamp
2020-01-29  16.389999    17.11       NaN
2020-01-30  15.490000    16.72       NaN
2020-01-31  18.840000    17.83       NaN
2020-02-03  17.969999    17.53       NaN
2020-02-04  16.049999    16.79       NaN
2020-02-05  15.150000    16.46       NaN
2020-02-06  14.960000    16.35       NaN
2020-02-07  15.470000    16.70       NaN
2020-02-10  15.040000    16.48       NaN
2020-02-11  15.180000    16.45  0.031739
2020-02-12  13.740000    16.11  0.052280
2020-02-13  14.150000    16.30  0.044862
2020-02-14  13.680000    16.11  0.064802
2020-02-18  14.830000    16.55  0.075743
2020-02-19  14.380000    16.27  0.099957
2020-02-20  15.560000    16.90  0.065938
2020-02-21  17.080000    17.33  0.008206
2020-02-24  25.030001    19.40 -0.055684
2020-02-25  27.850000    20.67 -0.047476
2020-02-26  27.559999    21.03 -0.036622
2020-02-27  39.160000    23.62 -0.060339
2020-02-28  40.110001    23.00 -0.056474
2020-03-02  33.419998    23.30 -0.034115
2020-03-03  36.820000    25.50 -0.038919
2020-03-04  31.990000    24.70 -0.028461
2020-03-05  39.619999    27.52 -0.053670
2020-03-06  41.939999    30.65 -0.062202
2020-03-09  54.459999    37.20 -0.072912
2020-03-10  47.299999    34.55 -0.055199
2020-03-11  53.900002    39.05 -0.063743
2020-03-12  75.470001    47.35 -0.071835
2020-03-13  57.830002    44.80 -0.032335
2020-03-16  82.690002    58.85 -0.048230
2020-03-17  75.910004    60.70 -0.029738
2020-03-18  76.449997    71.15 -0.011173
2020-03-19  72.000000    68.20 -0.008864
2020-03-20  66.040001    62.00 -0.011174

In [8]:
"<br><br> Short VIX Enter: %.2f, Short VIX Exit: %.2f; Long VIX Enter: %.2f, Long VIX Exit: %.2f"%(vix_enter, vix_exit, vix_buy_enter, vix_buy_exit)

'<br><br> Short VIX Enter: -0.03, Short VIX Exit: -0.05; Long VIX Enter: -0.07, Long VIX Exit: -0.06'

------------

In [14]:
pos_list = robinhood.my_trader.positions()["results"]

In [16]:
filter(lambda x: x["instrument"] == robinhood.get_instrument("VIXY")["url"].values[0], pos_list)

[{u'account': u'https://api.robinhood.com/accounts/5QS48912/',
  u'account_number': u'5QS48912',
  u'average_buy_price': u'13.3950',
  u'created_at': u'2018-02-05T19:47:45.005850Z',
  u'instrument': u'https://api.robinhood.com/instruments/869251ff-fb17-40c6-9d24-9ab7636dd3d6/',
  u'intraday_average_buy_price': u'13.3950',
  u'intraday_quantity': u'66.00000000',
  u'pending_average_buy_price': u'13.3950',
  u'quantity': u'66.00000000',
  u'shares_held_for_buys': u'0.00000000',
  u'shares_held_for_options_collateral': u'0.00000000',
  u'shares_held_for_options_events': u'0.00000000',
  u'shares_held_for_sells': u'0.00000000',
  u'shares_held_for_stock_grants': u'0.00000000',
  u'shares_pending_from_options_events': u'0.00000000',
  u'updated_at': u'2019-11-26T19:03:15.036738Z',
  u'url': u'https://api.robinhood.com/positions/5QS48912/869251ff-fb17-40c6-9d24-9ab7636dd3d6/'}]

In [17]:
def get_average_cost(self,symbol):
    tmp = filter(lambda x: x["instrument"] == self.get_instrument("VIXY")["url"].values[0], pos_list)
    if len(tmp) == 0:
        return 0
    else:
        return tmp["average_buy_price"]

In [6]:
robinhood.get_average_cost("VIXY")

Connection Successful

11.83

In [17]:
robinhood.get_my_position_beta_minute(sv=0.02).Mins_VaR.sum()

59.76928720939598

In [8]:
var_normal("VIXY",sv = 0.02)

All price data of Close is actually Adj Close
('Finished', 'VIXY')

1.2684683433172144

In [32]:
var_table.Mins_VaR.mean()

49.951694355976045

------

## VWAP

In [26]:
price = get_price_data(["KRNY"],method="intraday",robinhood=robingateway(),back_day=1)

price["Traded_Cash"] = price.Close * price.Volume

price["Traded_Cash_cum"] = price["Traded_Cash"].cumsum()

price["Volume_cum"] = price.Volume.cumsum()

price["VWAP"] = price["Traded_Cash_cum"]/price["Volume_cum"]

price

All price data of Close is actually Adj Close
('Finished', u'KRNY')

In [32]:
vwap = price["Traded_Cash"].sum()/price.Volume.sum()

In [3]:
vwap("MRNA",back_day=3)

All price data of Close is actually Adj Close
('Finished', u'MRNA')

60.83765624652283

In [11]:
vwap("SPWH",back_day=2)

All price data of Close is actually Adj Close
('Finished', u'SPWH')

14.477388212402133

In [5]:
realtimequote("FUTU").price

0   29.8700
Name: price, dtype: float64

In [10]:
get_trade_log("FUTU")

Connection Successful

   Hold_days   Price  Strategy Ticker           TimeStamp  size
0    35.0000 30.7300  momentum   FUTU 2020-07-06 07:47:37     9
1        nan 29.3600  momentum   FUTU 2020-07-07 06:16:43    -9
2        nan 30.7300    Manual   FUTU 2020-07-07 06:21:09     9
3    35.0000 29.6700  momentum   FUTU 2020-07-07 06:42:28    10

In [3]:
beta(["VIX"],interval ="minute",robinhood=robingateway())

method not correct

AttributeError: 'NoneType' object has no attribute 'rename'

In [3]:
i = "TBIO"

In [4]:
log = get_trade_log(i) 
if ( len(log)==0 or log["size"].sum()  == 0) and i not in trading_param["Long_Term_Tickers"]:
#         log_trade(i,tic_frame[tic_frame.Tickers == i].Sizes.values[0] ,da.get_quote_yahoo(i).regularMarketPrice.values[0], strategy_name)
    log_trade(i,tic_frame[tic_frame.Tickers == i].Sizes.values[0] ,robinhood.get_average_cost(i), strategy_name)
log = get_trade_log(i)    
log = log[log.Strategy==strategy_name]
log["Price"] = log.Price.astype(float)

Connection Successful
Connection Successful

In [3]:
get_price_data(["^VIX"],method = "day", back_day=10)

All price data of Close is actually Adj Close
Connection Successful
exceptions must be old-style classes or derived from BaseException, not NoneType
switching to realtimeday method
All price data of Close is actually Adj Close
('Finished', u'^VIX')
('Finished', '^VIX')

,index,adjClose,change,changeOverTime,changePercent,Close,TimeStamp,High,label,Low,Open,Ticker,Return,Fwd_Return
0,4,27.9400,0.1800,0.0065,0.6480,27.9400,2020-07-06,28.3300,"July 06, 20",24.9200,27.7600,^VIX,nan,0.0520
1,3,29.4300,0.6600,0.0229,2.2940,29.4300,2020-07-07,29.6300,"July 07, 20",27.2500,28.7700,^VIX,0.0506,-0.0470
2,2,28.0800,-0.8700,-0.0301,-3.0050,28.0800,2020-07-08,30.2000,"July 08, 20",27.2400,28.9500,^VIX,-0.0481,0.0412
3,1,29.2600,1.0800,0.0383,3.8330,29.2600,2020-07-09,31.4800,"July 09, 20",26.1100,28.1800,^VIX,0.0403,-0.0697
4,0,27.2900,0.0000,0.0000,0.0000,27.2900,2020-07-10,0.0000,"July 10, 20",0.0000,0.0000,^VIX,-0.0722,nan

In [3]:
sql = '''
select * from all_symbol.Screener_TOS

'''

mongod = mongo()

data = mongod.conn.get_data(sql)

Connection Successful

In [37]:
lowerbetter = screener.groupby(["Sector"]).agg({"P/S":"rank",'P/Cash':"rank",'P/E':"rank",'P/Free Cash Flow':"rank",'Analyst Recom':"rank",'Total Debt/Equity':"rank"},ascending = True, method = "First")

In [38]:
higherbetter.sort_values("EPS (ttm)")

,Insider Ownership,Gross Margin,Current Ratio,Sales growth quarter over quarter,Profit Margin,Quick Ratio,Performance (Week),Institutional Ownership,EPS (ttm),Operating Margin
Ticker,,,,,,,,,,
AVID,89.0000,67.0000,36.5000,9.0000,3.0000,30.5000,22.0000,64.0000,1.0000,23.0000
SAND,81.0000,nan,nan,117.0000,nan,nan,111.0000,42.0000,1.0000,nan
HNP,nan,58.0000,5.5000,74.0000,2.0000,12.5000,41.0000,1.0000,1.0000,4.0000
LPX,116.5000,21.0000,340.5000,198.0000,8.0000,328.0000,47.0000,314.0000,1.0000,9.0000
UGP,116.0000,5.0000,107.5000,97.0000,7.0000,104.5000,89.0000,10.5000,1.0000,11.5000
SELF,154.0000,58.0000,nan,92.0000,2.0000,nan,108.0000,11.0000,1.0000,37.0000
ATRS,136.5000,95.0000,116.5000,189.0000,13.5000,115.5000,44.0000,45.0000,1.0000,20.5000
KRUS,263.0000,68.5000,214.0000,261.0000,8.5000,233.5000,18.0000,54.0000,1.0000,3.0000
LWAY,97.0000,29.0000,86.5000,35.5000,6.0000,76.5000,93.0000,16.0000,1.0000,1.0000
AEHR,182.0000,149.0000,265.0000,282.0000,12.5000,216.0000,246.0000,39.0000,1.5000,15.0000
ATIF,715.0000,nan,60.0000,8.0000,154.0000,59.0000,933.0000,1.0000,1.5000,112.0000
LGC,nan,nan,nan,nan,nan,nan,837.0000,nan,1.5000,nan
DAKT,209.0000,44.0000,125.0000,177.0000,6.0000,84.0000,77.0000,82.0000,1.5000,9.0000
RNGR,85.5000,22.0000,39.0000,69.5000,9.0000,46.0000,18.0000,68.0000,2.0000,21.0000
GNE,63.0000,4.0000,72.0000,77.0000,4.0000,72.0000,4.0000,14.0000,2.0000,2.0000
DOGZ,nan,64.0000,86.5000,2.0000,nan,82.0000,108.0000,2.0000,2.0000,nan
XHR,88.5000,47.0000,nan,7.5000,1.0000,nan,78.0000,72.0000,2.5000,11.5000
FPI,157.0000,136.0000,nan,107.5000,13.5000,nan,75.0000,25.0000,2.5000,137.5000
LIQT,338.0000,102.0000,272.5000,376.0000,24.0000,283.5000,289.0000,80.0000,2.5000,7.0000
PZZA,227.5000,115.5000,33.5000,194.0000,3.0000,73.0000,251.0000,nan,2.5000,15.0000
ENG,364.0000,29.0000,186.5000,383.0000,28.0000,261.0000,288.0000,28.0000,2.5000,12.5000
AYRO,187.0000,nan,130.5000,280.0000,nan,187.5000,245.0000,4.0000,2.5000,nan
ENOB,214.0000,nan,182.0000,nan,nan,183.0000,116.5000,6.0000,3.0000,nan
GWRS,49.5000,57.0000,74.0000,70.0000,12.0000,74.0000,53.0000,20.0000,3.0000,47.0000
PING,125.0000,252.0000,260.0000,232.0000,4.0000,264.0000,229.0000,250.0000,3.0000,14.0000
MOXC,91.0000,nan,13.5000,nan,106.0000,16.0000,125.0000,1.0000,3.0000,nan
CNSL,49.5000,58.0000,17.5000,33.0000,2.0000,22.0000,44.0000,68.5000,3.0000,34.0000
ONE,94.0000,83.0000,5.5000,12.5000,22.0000,25.5000,119.0000,59.0000,3.0000,6.0000
CRHM,153.0000,nan,nan,15.0000,nan,nan,184.0000,50.0000,3.0000,nan
HQY,116.5000,96.5000,86.5000,204.0000,3.0000,nan,35.0000,nan,3.0000,24.5000
...,...,...,...,...,...,...,...,...,...,...
BMA,685.0000,nan,nan,48.0000,448.0000,nan,741.5000,269.0000,913.0000,234.0000
TRV,135.0000,nan,nan,594.0000,69.5000,nan,350.5000,788.0000,914.0000,54.0000
ITIC,312.5000,nan,nan,828.0000,107.0000,nan,18.0000,489.5000,915.5000,106.0000
MET,75.0000,nan,nan,743.5000,135.5000,nan,380.0000,747.5000,915.5000,97.0000
FDS,263.5000,22.0000,42.5000,616.0000,344.0000,42.5000,314.5000,894.5000,917.0000,152.0000
BTO,52.5000,nan,nan,661.5000,nan,nan,317.0000,217.0000,918.0000,nan
SPGI,75.0000,45.0000,21.5000,760.0000,485.0000,23.0000,526.0000,818.0000,919.0000,199.0000
RGA,171.0000,nan,nan,245.5000,41.5000,nan,168.5000,840.0000,920.0000,35.0000
EQH,110.5000,12.0000,nan,283.5000,470.5000,nan,416.0000,889.5000,921.0000,2.0000
CET,692.0000,nan,nan,106.5000,nan,nan,572.0000,124.0000,922.0000,nan
SBNY,423.5000,nan,nan,578.0000,405.0000,nan,436.0000,886.0000,923.0000,312.0000
PNC,135.0000,nan,nan,202.5000,499.0000,nan,91.0000,782.0000,924.0000,333.0000
IX,171.0000,13.0000,nan,202.5000,146.0000,nan,717.0000,19.0000,925.0000,64.0000
DHIL,393.5000,89.0000,nan,373.5000,419.0000,nan,194.0000,558.5000,926.0000,181.0000
ALL,135.0000,nan,nan,157.0000,92.0000,nan,327.0000,762.5000,927.0000,61.5000
BAP,683.0000,nan,nan,642.0000,379.5000,nan,470.0000,640.5000,928.0000,212.0000
MTB,154.0000,nan,nan,151.5000,489.5000,nan,195.0000,802.5000,929.0000,424.5000
HIFS,423.5000,nan,nan,695.0000,425.0000,nan,344.0000,407.0000,930.0000,237.0000
MMAC,393.5000,84.0000,nan,7.0000,nan,nan,69.5000,298.0000,931.0000,nan
RE,295.5000,nan,nan,511.0000,nan,nan,524.0000,914.0000,932.0000,nan
GS,154.0000,34.0000,nan,135.5000,141.5000,nan,408.5000,716.5000,933.0000,103.0000
SIVB,154.0000,nan,nan,578.0000,527.5000,nan,210.5000,881.5000,934.0000,510.0000
CACC,641.0000,nan,nan,712.5000,377.0000,nan,328.0000,681.0000,935.0000,201.0000
NWLI,135.0000,nan,nan,5.0000,147.5000,nan,635.0000,832.0000,936.0000,3.0000
BLK,333.0000,57.5000,nan,725.0000,411.0000,nan,503.0000,812.5000,937.0000,161.0000
AMP,154.0000,19.0000,nan,306.0000,390.0000,nan,479.0000,825.5000,938.0000,162.0000
FCNCA,662.0000,nan,nan,707.5000,402.5000,nan,360.0000,512.0000,939.0000,527.0000
BHF,135.0000,nan,nan,905.0000,473.5000,nan,296.0000,877.5000,940.0000,185.0000
BRK-A,686.0000,6.0000,nan,525.0000,37.5000,nan,299.0000,666.0000,941.0000,58.0000
BRK-B,98.5000,nan,nan,525.0000,nan,nan,303.5000,667.0000,942.0000,nan

In [42]:
screener.groupby(["Sector"])[["P/S",'P/Cash','P/E','P/Free Cash Flow','Analyst Recom','Total Debt/Equity']].rank(ascending = True,method = "first")

,P/S,P/Cash,P/E,P/Free Cash Flow,Analyst Recom,Total Debt/Equity
Ticker,,,,,,
A,146.0000,124.0000,127.0000,126.0000,116.0000,109.0000
AAON,366.0000,nan,337.0000,271.0000,330.0000,68.0000
AAP,150.0000,109.0000,185.0000,126.0000,110.0000,80.0000
AAPL,219.0000,185.0000,127.0000,131.0000,64.0000,243.0000
AAT,83.0000,91.0000,116.0000,nan,103.0000,80.0000
AB,595.0000,nan,507.0000,416.0000,205.0000,1.0000
ABB,280.0000,134.0000,339.0000,250.0000,203.0000,279.0000
ABBV,143.0000,nan,54.0000,58.0000,70.0000,nan
ABC,3.0000,41.0000,37.0000,33.0000,149.0000,160.0000
ABCB,340.0000,282.0000,573.0000,nan,35.0000,309.0000
ABEV,nan,nan,35.0000,nan,95.0000,nan
ABG,25.0000,53.0000,48.0000,12.0000,111.0000,212.0000
ABM,49.0000,291.0000,144.0000,123.0000,204.0000,182.0000
ABMD,194.0000,137.0000,158.0000,99.0000,133.0000,1.0000
ABR,42.0000,37.0000,73.0000,nan,90.0000,157.0000
ABT,145.0000,162.0000,140.0000,137.0000,57.0000,118.0000
ABTX,304.0000,318.0000,664.0000,244.0000,406.0000,445.0000
ACA,194.0000,163.0000,161.0000,100.0000,56.0000,104.0000
ACAM,nan,358.0000,381.0000,nan,nan,1.0000
ACB,nan,nan,165.0000,nan,nan,nan
ACBI,326.0000,187.0000,610.0000,56.0000,206.0000,286.0000
ACC,93.0000,144.0000,127.0000,34.0000,45.0000,81.0000
ACCO,50.0000,132.0000,20.0000,21.0000,nan,296.0000
ACGL,234.0000,523.0000,513.0000,88.0000,245.0000,364.0000
ACH,9.0000,19.0000,107.0000,30.0000,nan,101.0000
ACHC,26.0000,145.0000,70.0000,10.0000,134.0000,166.0000
ACIA,225.0000,110.0000,234.0000,193.0000,232.0000,1.0000
ACIW,132.0000,219.0000,194.0000,108.0000,35.0000,239.0000
ACLS,133.0000,64.0000,178.0000,136.0000,123.0000,113.0000
ACMR,261.0000,195.0000,218.0000,229.0000,51.0000,117.0000
...,...,...,...,...,...,...
XRX,25.0000,7.0000,19.0000,nan,252.0000,209.0000
XTLB,nan,nan,4.0000,nan,nan,56.0000
XYF,16.0000,130.0000,5.0000,nan,477.0000,135.0000
XYL,309.0000,234.0000,310.0000,239.0000,286.0000,254.0000
Y,79.0000,419.0000,928.0000,277.0000,244.0000,349.0000
YCBD,64.0000,39.0000,17.0000,nan,148.0000,57.0000
YELP,64.0000,27.0000,109.0000,29.0000,92.0000,23.0000
YETI,243.0000,203.0000,252.0000,142.0000,37.0000,206.0000
YIN,179.0000,481.0000,848.0000,nan,nan,136.0000
YNDX,102.0000,39.0000,105.0000,75.0000,29.0000,24.0000
YORW,77.0000,nan,68.0000,nan,19.0000,16.0000
YRD,14.0000,108.0000,17.0000,212.0000,510.0000,137.0000
YUM,264.0000,200.0000,191.0000,163.0000,181.0000,nan
YUMC,225.0000,158.0000,221.0000,169.0000,82.0000,35.0000
YY,63.0000,9.0000,103.0000,nan,21.0000,36.0000
ZBH,100.0000,74.0000,171.0000,47.0000,69.0000,140.0000
ZBRA,155.0000,271.0000,132.0000,84.0000,172.0000,211.0000
ZCMD,112.0000,62.0000,35.0000,162.0000,nan,58.0000
ZEAL,nan,nan,38.0000,nan,132.0000,nan
ZEUS,1.0000,83.0000,120.0000,2.0000,85.0000,64.0000
ZION,296.0000,180.0000,608.0000,213.0000,362.0000,389.0000
ZKIN,23.0000,31.0000,4.0000,nan,nan,38.0000
ZM,122.0000,100.0000,126.0000,nan,78.0000,25.0000
ZNGA,108.0000,52.0000,119.0000,73.0000,45.0000,26.0000
ZNH,76.0000,nan,154.0000,30.0000,nan,358.0000
ZTO,382.0000,208.0000,322.0000,243.0000,120.0000,67.0000
ZTR,869.0000,nan,657.0000,nan,nan,nan
ZTS,180.0000,nan,128.0000,130.0000,107.0000,183.0000
ZUMZ,111.0000,45.0000,114.0000,61.0000,134.0000,33.0000
ZYXI,198.0000,170.0000,177.0000,157.0000,108.0000,61.0000

In [21]:
tickers = get_open_opsition()
strategy_name = "momentum"


for i in tickers: 
    print (i)
    i.encode("ASCII")
    log = get_trade_log(i)
    log = log[log.Strategy==strategy_name]
    if len(log) == 0:
        continue
    #cost = (log.Price * log["size"] ).sum()/log["size"].sum()
    cost = float(log.Price.iloc[-1])
    holddays = log.Hold_days.iloc[-1]
    if datetime.now() - log.TimeStamp.iloc[-1] >= timedelta(hours=holddays) \
    and log["size"].sum() != 0 \
    and i not in trading_param["Long_Term_Tickers"]:
#             current_quote = round(realtimequote(i)["price"].iloc[0])
        current_quote = float(robinhood.my_trader.get_quote(i)["last_trade_price"])

        if ((current_quote- cost)/cost) < trading_param["momentum_cutloss"]:

            if robinhood.place_sell_bulk_checkup(ticker_list=[i],quantity_list=[log["size"].iloc[-1]],price_list=[current_quote])== "Trade Success!":
                log_trade(i,-log["size"].sum(), current_quote, strategy_name)
                send_email(body_html="",body_content="", title = "momentum Cut Losses " +str(i))

        elif ((current_quote- cost)/cost) > trading_param["momentum_harvest"]:

            if robinhood.place_sell_bulk_checkup(ticker_list=[i],quantity_list=[log["size"].iloc[-1]],price_list=[current_quote])== "Trade Success!":
                log_trade(i,-log["size"].sum(), current_quote, strategy_name)
                send_email(body_html="",body_content="", title = "momentum Harvast Profit "+str(i))

#             elif datetime.now() - log.TimeStamp.iloc[-1] > timedelta(days=  holddays  ):
        elif datetime.now() - log.TimeStamp.iloc[-1] > timedelta(days=  holddays/14  ):
            if robinhood.place_sell_bulk_checkup(ticker_list=[i],quantity_list=[log["size"].iloc[-1]],price_list=[current_quote])== "Trade Success!":
                log_trade(i,-log["size"].sum(), current_quote, strategy_name)
                send_email(body_html="",body_content="", title = "momentum reach hold days limit "+str(i))

Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
CCI
Connection Successful
DFIN
Connection Successful

ValueError: cannot convert float NaN to integer

In [24]:
get_open_opsition()

Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful

['CCI', 'DFIN', 'FCO', 'VIXY']

In [26]:
log.Hold_days.iloc[-1] != log.Hold_days.iloc[-1]

True

In [6]:
datetime.now().minute

2

In [17]:
datetime.now().minute

33