In [1]:
from my_libs_py3 import *

C:\Users\gli26\Anaconda2\envs\python3\lib\site-packages\pyfolio\pos.py:28: UserWarning: Module "zipline.assets" not found; mutltipliers will not be applied to position notionals.
  ' to position notionals.'

In [16]:
pytz.timezone('US/Pacific')

In [9]:
tickers = get_open_opsition()

Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful
Connection Successful

In [10]:
tickers

['HCM',
 'NRG',
 'ALTM',
 'DHT',
 'TNK',
 'PRDO',
 'LPG',
 'SRE',
 'ELP',
 'VIXY',
 'FCO',
 'GTN']

In [11]:
log = get_trade_log("VIXY")
log = log[log.Strategy=="vix_dayroll"]

Connection Successful

In [23]:
tzz=pytz.timezone('US/Pacific')

In [22]:
datetime.now(pytz.timezone('US/Pacific')) - log.TimeStamp.iloc[-1].replace(tzinfo=pytz.timezone('US/Pacific'))

Timedelta('0 days 00:27:15.795574')

In [28]:
 log.TimeStamp.iloc[-1].replace(tzinfo=tzz) #>= timedelta(hours=15)

Timestamp('2021-04-15 12:27:48.444000-0700', tz='US/Pacific')

In [15]:
log

,_id,Price,Strategy,Ticker,TimeStamp,size
0,6029df6a797a11517a00688e,14.2700,vix_dayroll,VIXY,2019-11-18 13:04:18+00:00,21
1,6029df6a797a11517a00688f,14.2700,vix_dayroll,VIXY,2019-11-18 13:15:14+00:00,21
2,6029df6a797a11517a006890,14.3000,vix_dayroll,VIXY,2019-11-18 13:24:49+00:00,20
3,6029df6a797a11517a006891,14.2700,vix_dayroll,VIXY,2019-11-19 07:03:59+00:00,21
4,6029df6a797a11517a006892,287.0000,vix_dayroll,VIXY,2019-11-20 08:23:06+00:00,-20
...,...,...,...,...,...,...
77,6029df6a797a11517a0068db,14.1400,vix_dayroll,VIXY,2020-12-23 10:14:47+00:00,56
78,6029df6a797a11517a0068dc,14.0500,vix_dayroll,VIXY,2021-01-15 07:07:57+00:00,-56
79,6029df6a797a11517a0068dd,15.1200,vix_dayroll,VIXY,2021-01-27 09:13:37+00:00,52
80,6029df6a797a11517a0068de,17.0500,vix_dayroll,VIXY,2021-01-29 09:21:36+00:00,-52
81,607893b46d930211c8cda4a9,8.1700,vix_dayroll,VIXY,2021-04-15 12:27:48.444000+00:00,97

In [2]:
robinhood=robingateway()

In [3]:
trading_param["cash_reserve"]

3000.0

In [7]:
mongod = mongo("all_symbol","minute_beta")
tos = pd.DataFrame(mongod.conn.table.find({},{"Refresh_Date":1}).sort("Refresh_Date",-1).limit(1))["Refresh_Date"].iloc[0]
my_beta_mins = pd.DataFrame(mongod.conn.table.find({"Refresh_Date":tos}))

Connection Successful

In [5]:
my_beta_mins

,_id,Day_Change,Weight,Mins_VaR,Day_VaR,Last_price,Beta,Refresh_Date,Volotity,Ticker,Quantity
0,605cc7756d93022830a89914,0.0000,0.5445,51.2410,"1,063.6469",1.2000,-0.0037,2021-03-25 10:25:09.903000+00:00,0.0934,ELP,"3,747.0000"
1,605cc7756d93022830a89915,0.0199,0.0570,3.8762,25.5971,13.0750,0.4188,2021-03-25 10:25:09.903000+00:00,0.0117,LPG,36.0000
2,605cc7756d93022830a89916,0.0178,0.1715,6.6940,66.5022,12.0000,0.4669,2021-03-25 10:25:09.903000+00:00,0.0076,PRDO,118.0000
3,605cc7756d93022830a89917,0.0095,0.0315,0.6379,6.1726,130.1900,0.0700,2021-03-25 10:25:09.903000+00:00,0.0062,SRE,2.0000
4,605cc7756d93022830a89918,0.0039,0.0618,4.5405,29.4842,14.1750,0.1197,2021-03-25 10:25:09.903000+00:00,0.0124,TNK,36.0000
5,605cc7756d93022830a89919,0.0149,0.1337,5.1925,43.7022,18.4000,0.0523,2021-03-25 10:25:09.903000+00:00,0.0084,GTN,60.0000

In [180]:
mongod = mongo("stocks_10minute","AAPL")

Connection Successful

In [194]:
pd.DataFrame(mongod.conn.table.find({"TimeStamp":{"$lt":datetime.now()}}))

,_id,Close,Fwd_Return,High,Low,Open,Return,Ticker,Time,TimeStamp,Volume
0,60298704797a11517aa96d9a,318.3000,nan,318.3700,316.4410,317.1100,nan,AAPL,160000,2020-05-27 16:00:00+00:00,25321791
1,60298704797a11517aa96d9b,317.1100,nan,317.3300,316.6700,316.7300,-0.0038,AAPL,153000,2020-05-27 15:30:00+00:00,22928387
2,60298704797a11517aa96d9c,316.9710,nan,317.0000,315.6222,316.0200,-0.0004,AAPL,150000,2020-05-27 15:00:00+00:00,21526558
3,60298704797a11517aa96d9d,316.0200,nan,316.4200,315.8250,315.8250,-0.0030,AAPL,143000,2020-05-27 14:30:00+00:00,20465476
4,60298704797a11517aa96d9e,315.3100,nan,315.4076,314.4867,315.3300,-0.0023,AAPL,140000,2020-05-27 14:00:00+00:00,19258850
...,...,...,...,...,...,...,...,...,...,...,...
2928,605cf2edca3e34f4890fe98e,119.5900,0.0082,119.9600,119.5500,119.9600,-0.0031,AAPL,140000,2021-03-25 14:00:00+00:00,3672315
2929,605cf2edca3e34f4890fe990,120.5800,0.0028,120.6100,119.4900,119.5900,0.0082,AAPL,143000,2021-03-25 14:30:00+00:00,4639003
2930,605cf2edca3e34f4890fe992,120.9200,-0.0026,121.1000,120.5500,120.5700,0.0028,AAPL,150000,2021-03-25 15:00:00+00:00,5635808
2931,605cf2edca3e34f4890fe994,120.6000,-0.0002,121.0800,120.5400,120.9200,-0.0027,AAPL,153000,2021-03-25 15:30:00+00:00,10238291
2932,605cf2edca3e34f4890fe996,120.5800,nan,120.6700,120.5100,120.5900,-0.0002,AAPL,160000,2021-03-25 16:00:00+00:00,1440174

In [ ]:
.find("TimeStamp":{"$gte":start_date,"$lte":end_date}).sort("TimeStamp",pymongo.ASCENDING)

In [107]:
log["TimeStamp"] = log["TimeStamp"].apply(lambda x: x.astimezone(pytz.timezone("US/Pacific")))

In [71]:
mongod = mongo("all_symbol","cantrade")
## This line gets the max refresh_date
tos = pd.DataFrame(mongod.conn.table.find({},{"Refresh_Date":1}).sort("Refresh_Date",-1).limit(1))["Refresh_Date"].iloc[0]
all_ticker = pd.DataFrame(mongod.conn.table.find({"Refresh_Date":tos}))

Connection Successful

In [95]:
mongod = mongo("all_symbol","momentum_sharp")
existing = mongod.conn.table.find({"Ticker":"AAPL","Refresh_Date":datetime.today()})

Connection Successful

In [96]:
pd.DataFrame(existing)

Empty DataFrame
Columns: []
Index: []

In [31]:
sqld=connect_sql("ken",readgateway(2),host="10.0.1.17")

In [30]:
llist = ['cantrade',
 
 'momentum',
 'momentum_sharp',
 'pair_not_same_length',
 'pair_trade_screen_save',
 'pair_trade_sharp',

 'screener_tos',
 'screenerModel',
 'screenermodel_tos',
 'screenerVol',
 'screenervol_tos']

In [1]:
mlist = ["cantrade","cantrade_backup","cantrade_tos","dist_momentum_sharp_tos",\
         "institutional ownership","momentum","momentum_sharp",\
        "pair_not_same_length","pair_trade_screen_save","pair_trade_sharp","minute_beta"]

In [ ]:
sqld.cursor.execute("use all_symbol")
mongod = mongo("all_symbol")
table_names = sqld.get_data("show tables")

# for i in table_names.Tables_in_all_symbol:
for i in llist:
    content = None
#     if i in mongod.conn.db.list_collection_names(): continue
    sql_count = sqld.get_data("select count(*) from all_symbol.`%s`"%i).iloc[0].iloc[0]
    mongod.conn.table = mongod.conn.db[i]
    mongo_count = mongod.conn.table.count_documents({})
    if sql_count == mongo_count: continue
#     llist.append(i)
#     continue
    print (i)
    content = sqld.get_data("select * from `%s`"%i)
    ## cast datetime.date to datetime
    for col in content.columns:
        if "datetime.date" in str(type(content[col].iloc[0])):
            content[col] = content[col].apply(lambda x: datetime.combine(x,datetime.min.time()))
## Pymongo has a limit of 10,000 row per time for upload    
    mongod.conn.table.drop()
    for i in range(0,len(content),5000):
        mongod.conn.frame_to_mongo(content.iloc[i:i+5000])

Connection Successful
cantrade_tos
dist_momentum_sharp_tos
minute_beta
momentum
momentum_sharp
pair_not_same_length
pair_trade_screen_save
pair_trade_sharp
screener

----------

In [2]:
mongod = mongo("all_symbol","screener")

tos = pd.DataFrame(mongod.conn.table.find({},{"Refresh_Date":1}).sort("Refresh_Date",-1).limit(1))["Refresh_Date"].iloc[0]
price = pd.DataFrame(mongod.conn.table.find({"Refresh_Date":tos}))

Connection Successful

In [3]:
price

,_id,20-Day Simple Moving Average,200-Day Simple Moving Average,50-Day Simple Moving Average,52-Week High,52-Week Low,Analyst Recom,Average Volume,Beta,Change,Change from Open,Company,Country,Current Ratio,Dividend Yield,EPS (ttm),EPS growth past 5 years,EPS growth quarter over quarter,EPS growth this year,Forward P/E,Gap,Gross Margin,Industry,Insider Ownership,Insider Transactions,...,P/B,P/Cash,P/E,P/Free Cash Flow,P/S,PEG,Payout Ratio,Performance (Month),Performance (Quarter),Performance (Week),Price,Profit Margin,Quick Ratio,Refresh_Date,Relative Strength Index (14),Relative Volume,Sales growth past 5 years,Sales growth quarter over quarter,Sector,Shares Outstanding,Target Price,Ticker,Total Debt/Equity,Volatility (Month),Volume
0,60517b2281db0e00dd11d0a1,0.0042,0.1518,-0.0042,-0.1021,1.0119,2.1000,"1,752.2100",1.0100,-0.0085,-0.0141,"Agilent Technologies, Inc.",USA,2.1000,0.0063,2.6000,0.1200,0.4810,-0.3160,28.5800,0.0057,0.5330,Diagnostics & Research,0.0030,-0.2190,...,7.9000,28.5300,47.6200,43.7300,6.8600,4.4100,0.2740,-0.0230,0.0440,0.0686,122.9900,0.1460,1.6000,2021-03-16 13:01:17+00:00,52.1700,0.6200,0.0570,0.1410,Healthcare,306.0000,138.5600,A,0.5200,0.0277,"1,078,425.0000"
1,60517b2281db0e00dd11d0a2,0.0881,0.7330,0.2339,-0.1020,4.7209,2.5000,"6,294.8400",2.7000,-0.0490,-0.0372,Alcoa Corporation,USA,1.6000,nan,-0.9200,0.2800,0.9870,0.8500,15.5200,-0.0122,0.1420,Aluminum,0.0080,-0.0049,...,1.7400,3.6700,nan,143.9100,0.6400,nan,nan,0.4511,0.2928,0.0903,29.5200,-0.0180,1.1000,2021-03-16 13:01:17+00:00,59.1400,0.8000,-0.0370,-0.0180,Basic Materials,186.0000,24.5900,AA,0.7400,0.0685,"5,018,555.0000"
2,60517b2281db0e00dd11d0a3,-0.0069,-0.0669,-0.0433,-0.1636,0.1905,nan,736.7600,nan,0.0012,-0.0006,Goldman Sachs Physical Gold ETF,USA,nan,nan,nan,nan,nan,nan,nan,0.0017,nan,Exchange Traded Fund,nan,nan,...,nan,nan,nan,nan,nan,nan,nan,-0.0517,-0.0569,0.0305,17.2500,nan,nan,2021-03-16 13:01:17+00:00,42.4000,0.3800,nan,nan,Financial,nan,nan,AAAU,nan,0.0108,"279,353.0000"
3,60517b2281db0e00dd11d0a4,-0.1335,1.4133,0.1952,-0.7843,5.9608,nan,"6,011.5700",1.9500,-0.0858,-0.0819,ATA Creativity Global,China,0.5000,nan,-0.6200,-0.4800,1.5490,-0.3770,nan,-0.0043,0.3450,Education & Training Services,0.1870,0.0000,...,4.0500,9.2000,nan,nan,6.6700,nan,nan,-0.1708,2.9555,0.1621,4.2600,-0.6830,0.5000,2021-03-16 13:01:17+00:00,48.2500,0.0400,-0.2250,0.0390,Consumer Defensive,34.4300,nan,AACG,0.0100,0.1240,"235,555.0000"
4,60517b2281db0e00dd11d0a5,-0.0930,0.0037,-0.0626,-0.2541,0.0914,nan,"2,639.1100",nan,-0.0132,-0.0142,Artius Acquisition Inc.,USA,0.1000,nan,-0.0000,nan,nan,nan,nan,0.0009,nan,Shell Companies,nan,nan,...,1.1000,872.7100,nan,nan,nan,nan,nan,-0.0595,0.0282,-0.0084,10.4500,nan,0.1000,2021-03-16 13:01:17+00:00,41.6100,0.6500,nan,nan,Financial,72.4500,nan,AACQ,0.0000,0.0586,"1,709,140.0000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7935,60517b2581db0e00dd11efa0,0.0176,0.2769,0.0370,-0.2398,4.1667,1.0000,376.6000,1.4600,-0.0379,-0.0396,Zovio Inc,USA,1.1000,nan,-1.5000,0.0010,-1.3030,0.1760,nan,0.0017,0.6570,Education & Training Services,0.0010,0.0315,...,3.2000,5.1300,nan,8.6000,0.4800,nan,nan,-0.0333,0.2975,0.1813,5.5800,-0.1230,1.1000,2021-03-16 13:01:17+00:00,52.7900,0.7700,-0.0670,-0.0330,Consumer Defensive,32.7000,nan,ZVO,0.0500,0.1031,"289,629.0000"
7936,60517b2581db0e00dd11efa1,-0.0252,-0.0337,-0.0337,-0.1005,0.0110,nan,309.1700,nan,-0.0008,-0.0010,Z-Work Acquisition Corp.,USA,nan,nan,nan,nan,nan,nan,nan,0.0002,nan,Shell Companies,nan,nan,...,nan,nan,nan,nan,nan,nan,nan,-0.0436,nan,-0.0036,10.1100,nan,nan,2021-03-16 13:01:17+00:00,42.2600,0.5300,nan,nan,Financial,nan,nan,ZWRKU,nan,0.0235,"164,128.0000"
7937,60517b2581db0e00dd11efa2,-0.0869,-0.1650,-0.2072,-0.4266,0.6650,1.7000,527.1600,1.0400,-0.0097,-0.0105,Zymeworks Inc.,Canada,5.3000,nan,-3.5700,-0.1610,0.5520,0.0630,nan,0.0009,nan,Biotechnology,0.0070,-0.2363,...,4.2600,3.8100,nan,nan,41.6100,nan,nan,-0.1706,-0.3487,0.0274,33.8500,nan,5.3000,2021-03-16 13:01:17+00:00,36.5500,0.4400,0.3220,7.2630,Healthcare,51.1400,56.6300,ZYME,0.0000,0.0576,"231,351.0000"
7938,60517b2581db0e00dd11efa3,0.0473,0.2416,0.1561,-0.4311,1.0078,2.0000,"5,615.4600",2.6200,-0.2717,-0.1395,"Zynerba Pharmaceuticals, Inc.",USA,5.3000,nan,-1.9400,0.0760,0.2900,-0.2690,nan,-0.1536,nan,Drug Manufacturers - Specialty & Generic,0.0310,0.0000,...,3.4300,4.9100,nan,nan,nan,nan,nan,0.1506,0.7230,0.6981,5.1200,nan,5.3000,2021-03-16 13:01:17+00:00,52.0700,0.8600,nan,nan,Healthcare,29.3200,7.2900,ZYNE,0.0000,0.1338,"4,815,907.0000"
7939,60517b2581db0e00dd11efa4,-0.0333,-0.0717,-0.0572,-0.4592,1.0271,2.2000,684.6400,0.8800,-0.0156,-0.0198,"Zynex, Inc.",USA,6.2000,nan,0.2600,0.3680,-0.4200,-0.0710,22.2200,0.0043,0.7830,Medical Devices,0.4030,0.0000,...,10.0200,14.6100,62.5700,nan,7.1500,nan,0.0000,-0.1530,0.2205,0.0055,16.0800,0.1130,5.4000,2021-03-16 13:01:17+00:00,46.3300,0.7000,0.4710,0.8030,Healthcare,34.7800,24.7000,ZYXI,0.0100,0.0696,"481,586.0000"

In [17]:
mongod = mongo("all_symbol","screener")

Connection Successful

In [23]:
pre = time.time()
a = pd.DataFrame(mongod.conn.table.aggregate([
    {"$group":{"_id":None,"Max_Date":{"$max":"$Refresh_Date"}}}]))
post = time.time()
print(post-pre)

57.822993516922

In [24]:
a

    _id                  Max_Date
0  None 2021-03-16 13:01:17+00:00

In [45]:
pre = time.time()
a = pd.DataFrame(mongod.conn.table.find({},{"Refresh_Date":1}).sort("Refresh_Date",-1).limit(1))["Refresh_Date"].iloc[0]
re = pd.DataFrame(mongod.conn.table.find({"Refresh_Date":a}))

post = time.time()
print(post-pre)

1.0910110473632812

In [10]:
mongod = mongo("all_symbol","momentum_sharp")

tos = pd.DataFrame(mongod.conn.table.find({},{"Refresh_Date":1}).sort("Refresh_Date",-1).limit(1))["Refresh_Date"].iloc[0]
candidates = pd.DataFrame(mongod.conn.table.find({"Refresh_Date":tos})).drop_duplicates()
candidates = candidates[candidates.Holding <30].sort_values("Sharp_Ratio",ascending=False)

Connection Successful

In [11]:
candidates

,_id,Ticker,End_Value,Sharp_Ratio,Lookback,Holding,Last_Buy_Date,Last_Buy_Price,Max_Return,Min_Return,Refresh_Date
1874,605158ef81db0e00dd9e51bd,HBIO,"2,182.2119",132.3069,70.0000,5.0000,2021-03-11 00:00:00+00:00,5.2200,-0.0380,-0.0393,2021-03-16 00:00:00+00:00
359,605158ef81db0e00dd9e4bd2,AZO,"2,099.8536",70.7420,65.0000,20.0000,2021-03-08 00:00:00+00:00,"1,220.0000",0.0071,0.0057,2021-03-16 00:00:00+00:00
3633,605158ef81db0e00dd9e589c,SFBS,"2,979.7000",57.7649,70.0000,20.0000,2021-02-19 00:00:00+00:00,45.8400,0.0833,0.0695,2021-03-16 00:00:00+00:00
3950,605158ef81db0e00dd9e59d9,TBX,"2,072.7977",53.6674,70.0000,20.0000,2021-02-18 00:00:00+00:00,24.4800,0.0116,0.0103,2021-03-16 00:00:00+00:00
2917,605158ef81db0e00dd9e55d0,NUVB,"2,339.7106",52.0380,20.0000,25.0000,2021-03-03 00:00:00+00:00,10.8500,-0.0530,-0.0590,2021-03-16 00:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...
1233,605158ef81db0e00dd9e4f3c,EMNT,"1,970.5126",-76.0150,10.0000,10.0000,2021-02-17 00:00:00+00:00,100.7500,-0.0003,-0.0008,2021-03-16 00:00:00+00:00
3988,605158ef81db0e00dd9e59ff,TFLO,"1,981.5123",-76.4523,15.0000,20.0000,2021-03-01 00:00:00+00:00,50.3000,0.0002,-0.0001,2021-03-16 00:00:00+00:00
461,605158ef81db0e00dd9e4c38,BIL,"1,989.9707",-92.0597,25.0000,25.0000,2021-02-22 00:00:00+00:00,91.5100,0.0001,0.0000,2021-03-16 00:00:00+00:00
3144,605158ef81db0e00dd9e56b3,PGR,"1,764.8385",-137.1627,45.0000,25.0000,2020-12-22 00:00:00+00:00,97.7000,-0.0556,-0.0574,2021-03-16 00:00:00+00:00
1879,605158ef81db0e00dd9e51c2,HCAR,"1,911.3505",-277.4208,10.0000,10.0000,2021-02-16 00:00:00+00:00,10.1900,-0.0235,-0.0238,2021-03-16 00:00:00+00:00

In [14]:
a

Empty DataFrame
Columns: []
Index: []

In [5]:
pre = time.time()
a = pd.DataFrame(mongod.conn.table.aggregate([
                                             {"$project":{"Max_Date":{"$let":{"vars":{"date":"$Refresh_Date"},
                                                                            "in":{"$max":"$$date"}
                                                                           
                                                                           }}}}])).limit(1)
post = time.time()
print(post-pre)

KeyboardInterrupt:

In [7]:
pre = time.time()
a = pd.DataFrame(mongod.conn.table.aggregate([{"$group":{"_id":"$id","Max_Date":{"$max":"$Refresh_Date"}}}]))
post = time.time()
print(post-pre)

KeyboardInterrupt:

In [15]:
mongod.conn.table.create_index([("Refresh_Date",pymongo.DESCENDING),("Ticker",pymongo.TEXT)],name="Ticker_Date")

'Ticker_Date'

In [18]:
mongod.conn.table.create_index("Refresh_Date")

'Refresh_Date_1'

In [ ]:
pre = time.time()
a = pd.DataFrame(mongod.conn.table.find_one({"$expr":{"%eq":{"Refresh_Date":{"$min":"$Refresh_Date"}}}}),index=[0])
post = time.time()
print(post-pre)

In [33]:
mongod.conn.table.

{'_id': ObjectId('6051733f81db0e00ddb00732'),
 '20-Day Simple Moving Average': 0.344,
 '200-Day Simple Moving Average': 0.7932,
 '50-Day Simple Moving Average': 0.4764,
 '52-Week High': -0.0016,
 '52-Week Low': 2.0033,
 'Analyst Recom': 1.7,
 'Average Volume': 424.05,
 'Beta': 1.12,
 'Change': 0.121,
 'Change from Open': 0.1121,
 'Company': 'Zynex, Inc.',
 'Country': 'USA',
 'Current Ratio': 4.4,
 'Dividend Yield': nan,
 'EPS (ttm)': 0.3,
 'EPS growth past 5 years': 0.278,
 'EPS growth quarter over quarter': 0.232,
 'EPS growth this year': -0.004,
 'Forward P/E': 25.66,
 'Gap': 0.0079,
 'Gross Margin': 0.797,
 'Industry': 'Medical Devices',
 'Insider Ownership': 0.074,
 'Insider Transactions': nan,
 'Institutional Ownership': 0.199,
 'Institutional Transactions': -0.0024,
 'LT Debt/Equity': 0.0,
 'Market Cap': 657.11,
 'Operating Margin': 0.219,
 'P/B': 25.85,
 'P/Cash': 45.01,
 'P/E': 61.99,
 'P/Free Cash Flow': 136.9,
 'P/S': 12.76,
 'PEG': nan,
 'Payout Ratio': 0.0,
 'Performance (Month)': 0.723,
 'Performance (Quarter)': 0.9115,
 'Performance (Week)': 0.1476,
 'Price': 18.35,
 'Profit Margin': 0.196,
 'Quick Ratio': 3.8,
 'Refresh_Date': datetime.datetime(2020, 5, 4, 0, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000002198670A8D0>),
 'Relative Strength Index (14)': 68.94,
 'Relative Volume': 4.06,
 'Sales growth past 5 years': 0.325,
 'Sales growth quarter over quarter': 0.652,
 'Sector': 'Healthcare',
 'Shares Outstanding': 35.81,
 'Target Price': 19.54,
 'Ticker': 'ZYXI',
 'Total Debt/Equity': 0.01,
 'Volatility (Month)': 0.0945,
 'Volume': 1719821.0}

In [25]:
db.coll.aggregate([
  {$match: {status: "A"}},
  {$group: {_id: "$cust_id", total: {$sum: "$amount"}}},
  {$sort: {total: -1}}
])

AttributeError: 'Connection' object has no attribute 'get_data'